version: 0.0
os: linux

files:
  - source: ./
    destination: /var/www/html
    overwrite: yes

hooks:
  ApplicationStart:
    - location: scripts/changepermission.sh
      timeout: 3600
  ValidateService:
    - location: scripts/status_apache.sh
      timeout: 3600
      runas: root
